export const THEMES = {
	default: {
		'ag-header-background-color':             'white',
		'ag-data-color':                          'black',
		'ag-header-foreground-color':             'black',
		'ag-background-color':                    'white',
		'ag-foreground-color':                    'black',
		'ag-row-hover':                           'rgb(233, 242, 254)',
		'ag-header-cell-moving-background-color': 'rgb(185, 189, 190)',
		'slab_table_row_even_background':         '#F4F4F4',
		'slab_table_row_odd_background':          'rgb(253, 253, 253)',
		'slab_background_primary':                'white',
		'slab_foreground_primary':                'black',
		'slab_modal_header_background':           'rgb(248, 248, 248)',
		'slab_modal_bottom_background':           'rgb(248, 248, 248)',
		'slab_component_border_color':            'rgb(185, 189, 190)',
		'slab_table_border_color':                'rgb(216,216,216)',
		'slab_table_row_selection_background':    'rgb(233, 242, 254)',
		'slab_tab_selection_background':          'white',
		'slab_table_row_hover_background':        'rgb(233, 242, 254)',
		'slab_table_row_selection_foreground':    'black',
		'slab_scrollbar_thumb_background':        'rgb(220, 220, 220)',
		'slab_scrollbar_width':                   '10px',
		'slab_scrollbar_height':                  '10px',
		'primary':                                'rgb(21, 143, 239)',
		'success':                                'rgb(194, 217, 93)',
		'warning':                                'rgb(255, 210, 54)',
		'danger':                                 'rgb(255, 73, 68)',
		'info':                                   'rgb(178, 140, 232)',
		'secondary':                              'rgb(170, 170, 170)',
		'primary_light':                          'rgb(112, 187, 245)',
		'primary_lighter':                        'rgb(165, 208, 255)',
		'success_light':                          'rgb(200, 221, 109)',
		'success_lighter':                        'rgb(206, 225, 125)',
		'warning_light':                          'rgb(255, 214, 74)',
		'warning_lighter':                        'rgb(255, 219, 94)',
		'danger_light':                           'rgb(255, 91, 87)',
		'danger_lighter':                         'rgb(255, 109, 105)',
		'text-color':                             'rgb(21, 143, 239)',
		'text-color-secondary':                   'rgb(255, 255, 255)'
	},
	dark:    {
		'ag-header-background-color':             'rgb(11, 42, 94)',
		'ag-data-color':                          'white',
		'ag-header-foreground-color':             'white',
		'ag-background-color':                    'rgb(34, 64, 110)',
		'ag-foreground-color':                    'white',
		'ag-row-hover':                           'rgb(59, 138, 142)',
		'ag-header-cell-moving-background-color': 'rgb(59, 138, 142)',
		'slab_table_row_even_background':         'rgb(46, 76, 122)',
		'slab_table_row_odd_background':          'rgb(5, 61, 112)',
		'slab_background_primary':                'rgb(34, 64, 110)',
		'slab_foreground_primary':                'white',
		'slab_modal_header_background':           'rgb(12, 31, 62)',
		'slab_modal_bottom_background':           'rgb(27, 51, 88)',
		'slab_component_border_color':            'rgb(93, 136, 187)',
		'slab_table_border_color':                'rgb(59, 96, 142)',
		'slab_table_row_selection_background':    'rgb(83, 118, 176)',
		'slab_tab_selection_background':          'rgb(11, 42, 94)',
		'slab_table_row_hover_background':        'rgb(59, 138, 142)',
		'slab_table_row_selection_foreground':    'white',
		'slab_scrollbar_thumb_background':        'rgb(83, 118, 176)',
		'slab_scrollbar_width':                   '10px',
		'slab_scrollbar_height':                  '10px',
		'primary':                                'rgb(80, 115, 175)',
		'success':                                'rgb(194, 217, 93)',
		'warning':                                'rgb(255, 210, 54)',
		'danger':                                 'rgb(255, 73, 68)',
		'info':                                   'rgb(178, 140, 232)',
		'secondary':                              'rgb(170, 170, 170)',
		'primary_light':                          'rgb(75, 122, 180)',
		'primary_lighter':                        'rgb(93, 136, 187)',
		'success_light':                          'rgb(200, 221, 109)',
		'success_lighter':                        'rgb(206, 225, 125)',
		'warning_light':                          'rgb(255, 214, 74)',
		'warning_lighter':                        'rgb(255, 219, 94)',
		'danger_light':                           'rgb(255, 91, 87)',
		'danger_lighter':                         'rgb(255, 109, 105)',
		'text-color':                             'rgb(255, 255, 255)',
		'text-color-secondary':                   'rgb(255, 255, 255)'
	}
};
