export const THEMES = {
	default: {
		'ag-header-background-color': 'white',
		'ag-data-color':              'black',
		'ag-header-foreground-color': 'black',
		'slab_table_row_even_background':  '#F4F4F4',
		'slab_table_row_odd_background':   'rgb(253, 253, 253)',
		'slab_background_primary':         'white',
		'slab_foreground_primary':         'black',
		'slab_modal_header_background':    'rgb(248, 248, 248)',
		'slab_component_border_color':     '#b9bdbe',
		'slab_table_border_color':         'rgb(216,216,216)',
		'slab_table_row_selection_background': 'rgb(200, 223, 252)',
		'slab_table_row_selection_foreground': 'black',
	},
	dark:    {
		'ag-header-background-color': 'rgb(34, 64, 110)',
		'ag-data-color':              'white',
		'ag-header-foreground-color': 'white',
		'slab_table_row_even_background':  'rgb(46, 76, 122)',
		'slab_table_row_odd_background':   'rgb(5, 61, 112)',
		'slab_background_primary':         'rgb(34, 64, 110)',
		'slab_foreground_primary':         'white',
		'slab_modal_header_background':    'rgb(15,31,61)',
		'slab_component_border_color':     '#3b608e',
		'slab_table_border_color':         '#3b608e',
		'slab_table_row_selection_background': '#7A2048',
		'slab_table_row_selection_foreground': 'white',
	}
};
